### PR TITLE
Restore child process exit behavior

### PR DESCRIPTION
**Pull request by mildmojo**
The Node.js `ChildProcess.exec` callback gets called after the
child process exits. This change moves the "on exit" code inside the
callback and removes the polling behavior. Seems to be working on the
Lexitron. Fixes transient failure to remove the loading screen.

### CODE REVIEW

**Comment by justinjams** [comment]
The reason for the polling and the on exit event binding were both because
the exec callback wasn't working consistently on John's machine. Binding a
cb to the on exit event behaved the exact same way as the exec cb. But my
machine never had trouble, and if it works for Lexi it works for me! :)

On Nov 20, 2013, at 12:36 AM, Tim notifications@github.com wrote:

The Node.js ChildProcess.exec callback gets called after the
child process exits. This change moves the "on exit" code inside the
callback and removes the polling behavior. Seems to be working on the

## Lexitron. Fixes transient failure to remove the loading screen.

You can merge this Pull Request by running

  git pull https://github.com/mildmojo/moonshot fix_process_exit

Or view, comment on, or merge it at:

  https://github.com/runjumpdev/moonshot/pull/16
Commit Summary
- Restores child process exit behavior.

File Changes
- _M_ games/akbb/lexitron.jsonhttps://github.com/runjumpdev/moonshot/pull/16/files#diff-0(4)
- _M_ source/lib/moonshot.jshttps://github.com/runjumpdev/moonshot/pull/16/files#diff-1(15)

Patch Links:
- https://github.com/runjumpdev/moonshot/pull/16.patch
- https://github.com/runjumpdev/moonshot/pull/16.diff

**Comment by mildmojo** [comment]
Yeah, the Lexitron had the opposite problem, where polling wasn't working reliably. Failing to call the callback or fire the exit event seems pretty broken; I wonder what caused that? That would be a huge failure—it would never re-enable joystick input, either.

I think we can automatically hide the loading screen after 30 seconds, too, so players pop back to the launcher page.

**Comment by justinjams** [comment]
We were able to reproduce the bug by running AKBB (always) and JPF (only
when exiting quickly after launching). I was trying to code my way out of
troubleshooting his machine! I looked over process docs and the code seemed
fine. We should take a look at the Node config on that machine.

I like that idea. Do you think it should do anything else after 30 seconds?
It could poll then, and maybe reboot on sign of game failure. Basically,
just in case our bug did reappear.

And, speaking of process watching... Do we need something to watch for
Moonshot to be running? I'll make a feature item later, I'm emailing from
my phone now.

On Nov 20, 2013, at 8:59 AM, Tim notifications@github.com wrote:

Yeah, the Lexitron had the opposite problem, where polling wasn't working
reliably. Failing to call the callback or fire the exit event seems pretty
broken; I wonder what caused that? That would be a huge failure—it would
never re-enable joystick input, either.

I think we can automatically hide the loading screen after 30 seconds, too,
so players pop back to the launcher page.

justinjams notifications@github.com wrote:

> The reason for the polling and the on exit event binding were both
> because
> the exec callback wasn't working consistently on John's machine.
> Binding a
> cb to the on exit event behaved the exact same way as the exec cb. But
> my
> machine never had trouble, and if it works for Lexi it works for me! :)
> 
> On Nov 20, 2013, at 12:36 AM, Tim notifications@github.com wrote:
> 
> The Node.js ChildProcess.exec callback gets called after the
> child process exits. This change moves the "on exit" code inside the
> callback and removes the polling behavior. Seems to be working on the
> 
> ## Lexitron. Fixes transient failure to remove the loading screen.
> 
> You can merge this Pull Request by running
> 
> git pull https://github.com/mildmojo/moonshot fix_process_exit
> 
> Or view, comment on, or merge it at:
> 
> https://github.com/runjumpdev/moonshot/pull/16
> Commit Summary
> - Restores child process exit behavior.
> 
> File Changes
> - _M_
>   games/akbb/lexitron.json<
>   https://github.com/runjumpdev/moonshot/pull/16/files#diff-0>(4)
> - _M_
>   source/lib/moonshot.js<
>   https://github.com/runjumpdev/moonshot/pull/16/files#diff-1>(15)
> 
> Patch Links:
> - https://github.com/runjumpdev/moonshot/pull/16.patch
> - https://github.com/runjumpdev/moonshot/pull/16.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/runjumpdev/moonshot/pull/16#issuecomment-28889681

—
Reply to this email directly or view it on
GitHubhttps://github.com/runjumpdev/moonshot/pull/16#issuecomment-28890751
.

**Comment by mildmojo** [comment]
```
We were able to reproduce the bug by running AKBB (always) and JPF (only when
exiting quickly after launching). I looked over process docs and the code seemed
fine. We should take a look at the Node config on that machine.
```

Yeah, I'd like to see it happen on John's machine so we could dig into it. Check to make sure the child process actually exits and doesn't go zombie or something. Maybe it's a node-webkit version issue?

I did get similar behavior when I shoved Artemis into my local tree and quit from the game's launcher window instead of the game proper. This is worth diagnosing.

```
And, speaking of process watching... Do we need something to watch for Moonshot to be running?
```

Yeah, I had a note about that in the README. It's probably worth adding something like that. We haven't done burn-in tests to see how the launcher performs after hours or days yet. Hopefully there aren't any major memory leaks.

**Comment by mildmojo** [comment]
I'm going to merge this because it reflects the code on the machine; we should keep looking at it, though. This is the heart of the launcher.

**Pull request merged**
