### PR TITLE
Loading games dynamically

### PR DESCRIPTION
**Pull request by justinjams**
Games should now include a .lex file, which is JSON format.  Changes are reflected in the updated README.md

### CODE REVIEW

**Comment by mildmojo** [comment]
Heh, while you were writing this, I was writing #6. This seems good for now. Have you tried it out?

**Comment by justinjams** [comment]
Yeah, that looks very familiar! It works fine in my environment. I wasn't 100% sure on the information I put in the .lex files, though. Mainly `mmug.lex` doesn't have your last name and I didn't know what to put in`fauna_fight.lex`.

**Comment by mildmojo** [comment]
Honestly, that's all placeholder stuff anyway. None of those games will actually be on the public Lexitron, they were just in there for testing.

**Comment by justinjams** [comment]
I noticed this little bug while moving stuff to Reveal. Now I'm serious when I say it works fine!

**Comment by mildmojo** [comment]
Mrrrrrrged. In the long run, I think `.json` will be more straightforward than a custom file extension for the manifest files.

**Comment by justinjams** [comment]
I know you're right, but it makes me feel so special to make up file types. Thanks!

**Pull request merged**
